# Generated by Django 5.2 on 2025-05-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug_category", models.SlugField(blank=True, editable=False)),
                (
                    "icons",
                    models.ImageField(
                        blank=True, default="category.png", upload_to="category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug_dev", models.SlugField(blank=True, editable=False)),
                (
                    "dev_img",
                    models.ImageField(
                        blank=True, default="developer.png", upload_to="developer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=260)),
                ("fill", models.TextField()),
                (
                    "images",
                    models.ImageField(
                        blank=True, default="article.png", upload_to="service"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug_serv", models.SlugField(blank=True, editable=False)),
                ("publish", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueservice.category",
                    ),
                ),
                (
                    "develop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueservice.developer",
                    ),
                ),
            ],
        ),
    ]
