# Generated by Django 5.2 on 2025-04-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueservice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug_category",
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="developer",
            name="slug_dev",
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="service",
            name="slug_serv",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
