# Generated by Django 5.2 on 2025-04-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcategory",
            name="slug_book_category",
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="bookcollection",
            name="slug_book",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
